# Storyplex Analytics - Kubernetes Service
apiVersion: v1
kind: Service
metadata:
  name: storyplex-api
spec:
  type: NodePort
  selector:
    app: storyplex-analytics
  ports:
    - port: 80
      targetPort: 8000
